# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b678da2884d32fdcb03661b67eb3b26436b1a1c9a0a715d9627eca72b37d6d9d1c1f8883254601d9eb5d5eaca9255dac98bf63bca79653bae1a7a61eac6d067

test:
  secret_key_base: 83766a72c960ac4bef72f322067c20b3d0359b041e90ad76362eee48c66544822146fa6bdd7373c1a435e46d4a503ac4327c537215d144d46a686a63fd7316e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
